services:
  service: 
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    ports:
      - 8000:8000

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local